---

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: user | ansible | group
      tags: always
      group:
        name: ansible
        state: present

    - name: user | ansible |  create
      tags: always
      user:
        name: ansible
        groups: root
        state: present
        createhome: yes
        shell: /bin/bash

    - name: user | ansible | ssh pub key
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7ZKCfGHSEDKqwD7MuL/8y0G2rxSyFESJwkcm17vcT8 ansible"
        state: present

    - name: user | ansible | sudoers
      tags: always
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: user | bean | group
      tags: always
      group:
        name: bean
        state: present

    - name: user | bean | create
      tags: always
      user:
        name: bean
        group: bean
        state: present
        createhome: yes
        shell: /bin/bash

    - name: user | bean | ssh pub key
      tags: always
      authorized_key:
        user: bean
        key: 
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIefOlgTs7w/n/wGGv4LWhOfVwzwmbsQx6VB6/cy/Jo acer_bean"
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIx7pxPl9zOUCRwBoo9EfDT9Knx/ssU01FFftP6M21Kj bean@rivendell"
        state: present

    - name: user | bean | sudoers
      tags: always
      copy:
        src: sudoer_bean
        dest: /etc/sudoers.d/bean
        owner: root
        group: root
        mode: 0440
