---

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: user | ansible | group
      tags: always
      group:
        name: ansible
        state: present

    - name: user | ansible |  create
      tags: always
      user:
        name: ansible
        groups: root
        state: present
        createhome: yes
        shell: /bin/bash

    - name: user | ansible | ssh pub key
      tags: always
      authorized_key:
        user: ansible
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7ZKCfGHSEDKqwD7MuL/8y0G2rxSyFESJwkcm17vcT8 ansible"
        state: present

    - name: user | ansible | sudoers
      tags: always
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: user | bean | group
      tags: always
      group:
        name: bean
        state: present

    - name: user | bean | create
      tags: always
      user:
        name: bean
        group: bean
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Update SSH port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Port '
        line: 'Port 20'
      notify: Restart SSH

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Enable key authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Add SSH public keys for user bean
      debug:
        msg: "Adding SSH public keys for user bean"
      tags: always

    - name: Install bean's SSH public keys
      tags: always
      authorized_key:
        user: bean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIefOlgTs7w/n/wGGv4LWhOfVwzwmbsQx6VB6/cy/Jo acer_bean"
        state: present

    - name: Install bean's SSH public keys
      tags: always
      authorized_key:
        user: bean
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIx7pxPl9zOUCRwBoo9EfDT9Knx/ssU01FFftP6M21Kj bean@rivendell"
        state: present


    - name: Debug message after installing SSH keys
      debug:
        msg: "SSH keys for user bean installed successfully"
      tags: always


    - name: user | bean | sudoers
      tags: always
      copy:
        src: sudoer_bean
        dest: /etc/sudoers.d/bean
        owner: root
        group: root
        mode: 0440

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
